#!/usr/bin/env bash

set -e

export DOCKER_IP=0.0.0.0

# docker-machine doesn't exist in Linux, assign default ip if it's not set
DOCKER_IP=${DOCKER_IP:-0.0.0.0}

echo 'Docker Ip set to ' $DOCKER_IP

# Remove existing containers
docker-compose stop online-store

docker-compose rm -f

#start the couchbase server
docker-compose up --build -d couchbase-store

# Build the project and docker images
./gradlew clean build

# rebuild the spring boot container
docker-compose up --build -d online-store


# Attach to the log output of the cluster
docker-compose logs -f